# Site settings
title: SixTeenBlog
header-img: img/home-bg.jpg
email: 929845256@qq.com
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://yourdomain.com"
twitter_username:
github_username:  16sixteen
facebook_username: 


# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'tags'

# Build settings
markdown: rdiscount
rdiscount:
extensions: ["fenced_code_blocks", "tables", "highlight", "strikethrough"]
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
