# Site settings
title: SixTeenBlog
header-img: img/home-bg.jpg
email: 929845256@qq.com
description: "Here is SixTeenBlog, Welcome!"
baseurl: ""
url: "http://yourdomain.com"
twitter_username:
github_username:  16sixteen
facebook_username: 


# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'tags'
timezone: Asia/Shanghai
futrue: enable
permalink: /:categories/:title
# Build settings
#markdown: redcarpet
markdown: kramdown
excerpt_separator: ""
#jekyll3.0 not support other highlight
#highlighter: pygments
highlighter: rouge
#permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
